M48
; DRILL file {KiCad 9.0.6} date 2025-12-25T18:23:02+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-25T18:23:02+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X172.0Y-97.0
X172.0Y-188.5
X238.0Y-97.0
X238.0Y-188.5
M30
